'use client'

import { ISchedule } from '@/app/models/ISchedule'
import { Button } from '@/components/ui/button'
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { SearchBar } from '@/components/ui/searchbar'
import { Pen, Trash } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useDownloadExcel } from 'react-export-table-to-excel'
import { enhancedPrint, getCurrentAcademicYear, getCurrentSemester } from '@/app/lib/printUtils'
import { formatScheduleEntry, type ScheduleDisplayData } from '@/lib/utils'
import EditScheduleDialog from './modal/EditSchedule'
import DeleteScheduleDialog from './modal/DeleteSchedule'
import AddScheduleDialog from './modal/AddSchedule'

interface ISessionData {
  userId: number;
  role: string;
  email: string;
  name: string;
}

export default function SchedulesTable() {
  const tableRef = useRef<HTMLTableElement>(null)
  const [filter, setFilter] = useState("")
  const [schedules, setSchedules] = useState<ISchedule[]>([]);
  const [session, setSession] = useState<ISessionData | null>(null);

  // Fetch session
  useEffect(() => {
    async function fetchSession() {
      try {
        const res = await fetch('/api/session');
        const data = await res.json();
        setSession(data ?? null);
      } catch (error) {
        console.error('Failed to load session:', error);
      }
    }

    fetchSession();
  }, []);

  // Fetch schedules
  useEffect(() => {
    async function fetchData() {
      try {
        console.log('Fetching schedules for SchedulesTable');
        const res = await fetch('/api/schedules');
        
        if (!res.ok) {
          console.error(`Schedules API failed: ${res.status} ${res.statusText}`);
          throw new Error('Failed to fetch schedules');
        }
        
        const result = await res.json();
        console.log('SchedulesTable API response:', result);
        
        // Handle the API response format { success: true, data: [...] }
        if (result.success && Array.isArray(result.data)) {
          setSchedules(result.data);
          console.log('Set schedules data:', result.data);
        } else if (Array.isArray(result)) {
          // Fallback for direct array response
          setSchedules(result);
          console.log('Set schedules data (direct array):', result);
        } else {
          console.error('Invalid schedules response format:', result);
          setSchedules([]);
        }
      } catch (error) {
        console.error('Error fetching schedules:', error);
        setSchedules([]); // Ensure schedules is always an array
      }
    }

    if (session) fetchData();
  }, [session]);

  
  // Ensure schedules is always an array before filtering
  const safeSchedules = Array.isArray(schedules) ? schedules : [];
  
  const filteredSchedules = safeSchedules.filter(schedule => {
    // First filter by role
    let roleMatch = false;
    if (session?.role === "admin" || session?.role === "dean") {
      roleMatch = true;
    } else if (session?.role === "instructor") {
      roleMatch = schedule.InstructorID === session?.userId;
    }
    
    if (!roleMatch) return false;
    
    // Then filter by search term if provided
    if (!filter) return true;
    
    return (
      schedule.Course?.toLowerCase().includes(filter.toLowerCase()) ||
      schedule.Section?.toLowerCase().includes(filter.toLowerCase()) ||
      schedule.SubjectCode?.toLowerCase().includes(filter.toLowerCase()) ||
      schedule.SubjectName?.toLowerCase().includes(filter.toLowerCase())
    );
  });
  
  console.log('Filtered schedules:', filteredSchedules);
  
  function handlePrint() {
    if (!tableRef.current) {
      alert('Table not ready for printing.');
      return;
    }

    enhancedPrint(tableRef, {
      title: 'CLASS SCHEDULES',
      subtitle: 'Academic Schedule Report',
      department: 'Academic Affairs Office',
      academicYear: getCurrentAcademicYear(),
      semester: getCurrentSemester(),
      additionalInfo: {
        'Total Schedules': filteredSchedules.length.toString(),
        'Report Date': new Date().toLocaleDateString(),
        'Generated By': session?.name || 'System Administrator'
      }
    });
  }

  const { onDownload } = useDownloadExcel({
    currentTableRef: tableRef.current,
    filename: `Class_Schedules_${new Date().toISOString().split('T')[0]}`,
    sheet: 'Schedules'
  });

  function reloadData() {
    location.reload();
  }

  return (
    <>
      <div className='flex flex-col sm:flex-row gap-3 mb-5'>
        <SearchBar
          placeholder="Search by course or section..."
          value={filter}
          onChange={setFilter}
          className="w-full"
        />
        <div className='flex gap-2 flex-shrink-0'>
          <Button onClick={handlePrint} variant="outline">Print Report</Button>
          <Button onClick={onDownload} variant="outline">Export to Excel</Button>
          <AddScheduleDialog onAdd={reloadData}/>
        </div>
      </div>

      <div className='overflow-hidden rounded-2xl border'>
        <Table ref={tableRef}>
          <TableCaption className="no-print">Class schedule listing</TableCaption>
          <TableHeader>
            <TableRow className='bg-gray-100'>
              <TableHead>Schedule ID</TableHead>
              <TableHead>Course</TableHead>
              <TableHead>Instructor ID</TableHead>
              <TableHead>Section</TableHead>
              <TableHead>Year Level</TableHead>
              <TableHead>Schedule</TableHead>
              <TableHead className='text-center no-print'>Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredSchedules.map((sched, idx) => (
              <TableRow key={idx} className='even:bg-gray-50'>
                <TableCell>{sched.ScheduleID}</TableCell>
                <TableCell>{sched.Course}</TableCell>
                <TableCell>{sched.InstructorID}</TableCell>
                <TableCell>{sched.Section}</TableCell>
                <TableCell>{sched.YearLevel}</TableCell>
                <TableCell>
                  <div className="space-y-1">
                    <div className="font-medium text-gray-900">{sched.Room}</div>
                    <div className="text-sm text-gray-600">
                      {formatScheduleEntry({
                        Room: sched.Room ?? undefined,
                        Day: sched.Day ?? undefined,
                        Time: sched.Time ?? undefined,
                        Lecture: sched.Lecture ?? undefined,
                        Laboratory: sched.Laboratory ?? undefined,
                        ClassType: sched.ClassType ?? undefined
                      })}
                    </div>
                  </div>
                </TableCell>
                <TableCell className='flex gap-2 items-center justify-center no-print'>
                  <EditScheduleDialog onUpdated={reloadData} schedule={sched} />
                  <DeleteScheduleDialog onDeleted={reloadData} scheduleId={sched.ScheduleID}/>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </>
  )
}
