'use client'
import React, { useState, useEffect } from 'react'
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { IStudent } from '@/app/models/IUser'
import { brandedToast } from '@/components/ui/branded-toast'
import { Eye, EyeOff } from 'lucide-react'

interface Course {
  CourseID: number
  CourseCode: string
  CourseName: string
  Description: string
  TotalUnits: number
  DurationYears: number
  Status: string
}

export default function AddStudentDialog({ onAdded }: { onAdded: () => void }) {
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [open, setOpen] = useState(false)
  const [courses, setCourses] = useState<Course[]>([])
  const [showPassword, setShowPassword] = useState(false)
  const [isLoadingCourses, setIsLoadingCourses] = useState(false)
  const [validationErrors, setValidationErrors] = useState<{ [key: string]: string }>({})
  const [emailManuallyEdited, setEmailManuallyEdited] = useState(false)

  // Fetch courses when modal opens
  useEffect(() => {
    if (open) {
      fetchCourses()
      setEmailManuallyEdited(false)
    }
  }, [open])

  const fetchCourses = async () => {
    try {
      setIsLoadingCourses(true)
      const response = await fetch('/api/courses')
      if (response.ok) {
        const coursesData = await response.json()
        setCourses(coursesData)
      } else {
        console.error('Failed to fetch courses')
      }
    } catch (error) {
      console.error('Error fetching courses:', error)
    } finally {
      setIsLoadingCourses(false)
    }
  }

  const [form, setForm] = useState<IStudent>({
    UserID: 0,
    StudentID: '',
    FirstName: '',
    LastName: '',
    MiddleName: '',
    EmailAddress: '',
    Password: '',
    Role: 'student',
    Sex: '',
    Status: 'active',
    IsPWD: false,
    ContactNumber: '',
    StudentNumber: '', // This will be auto-generated by the API
    Course: '',
    YearLevel: 1,
    Section: '',
    DateOfEnrollment: new Date().toISOString().split('T')[0],
    GuardianName: '',
    GuardianContact: '',
    Address: '',
  })

  // Validation functions
  const validateEmail = (email: string): string => {
    if (!email.trim()) return 'Email is required'
    const emailLower = email.trim().toLowerCase()
    if (!/@cca\.edu\.ph$/i.test(emailLower)) {
      return 'Email must end with @cca.edu.ph'
    }
    return ''
  }

  const makeStudentEmail = (first: string, last: string): string => {
    const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '')
    const fi = norm(first)
    const ln = norm(last)
    if (!fi && !ln) return ''
    // Use firstname.lastname format, same as instructors
    return `${fi}.${ln}@cca.edu.ph`
  }

  // Function to check if email exists and generate unique variant
  const generateUniqueEmail = async (baseEmail: string): Promise<string> => {
    try {
      const response = await fetch(`/api/users?email=${encodeURIComponent(baseEmail)}`)
      const data = await response.json()

      if (!data.exists) {
        return baseEmail
      }

      // Email exists, try with number suffix
      const [localPart, domain] = baseEmail.split('@')
      let counter = 1
      let newEmail = `${localPart}${counter}@${domain}`

      // Try up to 100 variations
      while (counter < 100) {
        const checkResponse = await fetch(`/api/users?email=${encodeURIComponent(newEmail)}`)
        const checkData = await checkResponse.json()

        if (!checkData.exists) {
          return newEmail
        }

        counter++
        newEmail = `${localPart}${counter}@${domain}`
      }

      // Fallback: use timestamp
      return `${localPart}${Date.now().toString().slice(-4)}@${domain}`
    } catch (error) {
      // If API fails, return base email and let backend handle it
      console.error('Email check failed:', error)
      return baseEmail
    }
  }

  const validateContactNumber = (contact: string): string => {
    if (!contact.trim()) return 'Contact number is required'
    if (!/^\d+$/.test(contact)) return 'Contact number must contain only digits'
    if (!/^09\d{9}$/.test(contact)) {
      return 'Contact number must be exactly 11 digits starting with 09'
    }
    return ''
  }

  const validateGuardianContact = (contact: string): string => {
    if (!contact.trim()) return '' // Guardian contact is optional
    if (!/^\d+$/.test(contact)) return 'Guardian contact must contain only digits'
    if (contact.length < 7 || contact.length > 15) {
      return 'Guardian contact must be 7-15 digits'
    }
    return ''
  }

  const validateForm = (): boolean => {
    const errors: { [key: string]: string } = {}

    // Required field validations
    if (!form.FirstName.trim()) errors.FirstName = 'First name is required'
    if (!form.LastName.trim()) errors.LastName = 'Last name is required'
    if (!form.EmailAddress.trim()) errors.EmailAddress = 'Email is required'
    if (!form.Password.trim()) errors.Password = 'Password is required'
    if (!form.Sex) errors.Sex = 'Sex is required'
    if (!form.Course) errors.Course = 'Course is required'
    if (!form.Section.trim()) errors.Section = 'Section is required'
    if (!form.ContactNumber?.trim()) errors.ContactNumber = 'Contact number is required'

    // Email validation
    const emailError = validateEmail(form.EmailAddress)
    if (emailError) errors.EmailAddress = emailError

    // Contact number validation
    if (form.ContactNumber) {
      const contactError = validateContactNumber(form.ContactNumber)
      if (contactError) errors.ContactNumber = contactError
    }

    // Guardian contact validation
    if (form.GuardianContact) {
      const guardianContactError = validateGuardianContact(form.GuardianContact)
      if (guardianContactError) errors.GuardianContact = guardianContactError
    }

    setValidationErrors(errors)
    return Object.keys(errors).length === 0
  }

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    const { name } = e.target
    let { value } = e.target

    // Normalize contact number: allow digits only, limit to 11
    if (name === 'ContactNumber') {
      value = value.replace(/\D+/g, '').slice(0, 11)
    }

    const updatedForm = {
      ...form,
      [name]: name === 'YearLevel' ? Number(value) :
        name === 'IsPWD' ? (value === 'true') : value,
    }

    setForm(updatedForm)

    // Auto-generate email when typing name if user hasn't edited email manually
    if ((name === 'FirstName' || name === 'LastName') && !emailManuallyEdited) {
      const suggested = makeStudentEmail(
        name === 'FirstName' ? value : updatedForm.FirstName,
        name === 'LastName' ? value : updatedForm.LastName
      )
      if (suggested) {
        // Check for duplicates and generate unique email
        generateUniqueEmail(suggested).then((uniqueEmail) => {
          setForm(prev => ({ ...prev, EmailAddress: uniqueEmail }))
          const emailError = validateEmail(uniqueEmail)
          setValidationErrors(prev => ({ ...prev, EmailAddress: emailError || '' }))
        })
      }
    }

    // Validate email or contact number in real-time
    if (name === 'EmailAddress') {
      setEmailManuallyEdited(true)
      const emailError = validateEmail(updatedForm.EmailAddress);
      setValidationErrors(prev => ({
        ...prev,
        EmailAddress: emailError || ''
      }));
    } else if (name === 'ContactNumber') {
      const contactError = validateContactNumber(updatedForm.ContactNumber || '');
      setValidationErrors(prev => ({
        ...prev,
        ContactNumber: contactError || ''
      }));
    } else if (name === 'GuardianContact') {
      const guardianContactError = validateGuardianContact(updatedForm.GuardianContact || '');
      setValidationErrors(prev => ({
        ...prev,
        GuardianContact: guardianContactError || ''
      }));
    } else {
      // Clear validation error for other fields when user starts typing
      if (validationErrors[name]) {
        setValidationErrors(prev => {
          const newErrors = { ...prev }
          delete newErrors[name]
          return newErrors
        })
      }
    }
  }

  const resetForm = () => {
    setForm({
      UserID: 0,
      StudentID: '',
      FirstName: '',
      LastName: '',
      MiddleName: '',
      EmailAddress: '',
      Password: '',
      Role: 'student',
      Sex: '',
      Status: 'active',
      IsPWD: false,
      ContactNumber: '',
      StudentNumber: '',
      Course: '',
      YearLevel: 1,
      Section: '',
      DateOfEnrollment: new Date().toISOString().split('T')[0],
      GuardianName: '',
      GuardianContact: '',
      Address: '',
    })
    setValidationErrors({})
    setEmailManuallyEdited(false)
  }

  const handleSubmit = async (e?: React.FormEvent) => {
    e?.preventDefault() // Prevent form default submission
    if (isSubmitting) return // Prevent double submission

    // Validate form before submission
    if (!validateForm()) {
      return
    }

    try {
      setIsSubmitting(true)
      const res = await fetch('/api/students', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(form),
      })

      if (!res.ok) {
        const errorData = await res.json().catch(() => ({ error: 'Unknown error' }));
        console.error('Server error:', errorData);
        throw new Error(errorData.details || errorData.error || 'Failed to create student');
      }

      const result = await res.json()
      brandedToast.success(
        `Student added successfully! Student ID: ${result.PrefixedID}, Student Number: ${result.StudentNumber}`,
        { title: 'Success' }
      )

      // Reset form and close modal after successful submission
      resetForm()
      setEmailManuallyEdited(false)
      setOpen(false)
      onAdded()
    } catch (error) {
      console.error('Create failed:', error)
      brandedToast.error(
        error instanceof Error ? error.message : 'Unknown error',
        { title: 'Failed to create student' }
      )
    } finally {
      setIsSubmitting(false)
    }
  }

  // Check if form is valid for submit button state
  const isFormValid = () => {
    return form.FirstName.trim() &&
      form.LastName.trim() &&
      form.EmailAddress.trim() &&
      form.Password.trim() &&
      form.Sex &&
      form.Course &&
      form.Section.trim() &&
      form.ContactNumber?.trim() &&
      !validateEmail(form.EmailAddress) &&
      (form.ContactNumber ? !validateContactNumber(form.ContactNumber) : true) &&
      (form.GuardianContact ? !validateGuardianContact(form.GuardianContact) : true)
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>Add Student</Button>
      </DialogTrigger>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Add Student</DialogTitle>
          <DialogDescription>Enter new student information.</DialogDescription>
        </DialogHeader>

        <form id="add-student-form" onSubmit={handleSubmit} className="space-y-4 mt-4 max-h-96 overflow-y-auto">
          <div className="grid grid-cols-2 gap-4">
            <Input name="FirstName" placeholder="First Name" value={form.FirstName} onChange={handleChange} required />
            <Input name="LastName" placeholder="Last Name" value={form.LastName} onChange={handleChange} required />
          </div>
          <Input name="MiddleName" placeholder="Middle Name" value={form.MiddleName} onChange={handleChange} />
          <div>
            <Input
              name="EmailAddress"
              placeholder="Email Address"
              type="email"
              value={form.EmailAddress}
              onChange={handleChange}
              required
              className={validationErrors.EmailAddress ? 'border-red-500' : ''}
            />
            {validationErrors.EmailAddress && (
              <p className="text-red-500 text-sm mt-1">{validationErrors.EmailAddress}</p>
            )}
          </div>
          <div className="space-y-2">
            <div className="flex gap-2">
              <div className="flex-1 relative">
                <Input
                  name="Password"
                  placeholder="Password"
                  type={showPassword ? "text" : "password"}
                  value={form.Password}
                  onChange={handleChange}
                  required
                  className="pr-10"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700"
                >
                  {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                </button>
              </div>
              <Button
                type="button"
                variant="outline"
                onClick={() => setForm(prev => ({ ...prev, Password: '12345678' }))}
                className="whitespace-nowrap flex-shrink-0"
              >
                Use Default
              </Button>
            </div>
          </div>
          <div>
            <Input
              name="ContactNumber"
              placeholder="Contact Number (09xxxxxxxxx)"
              value={form.ContactNumber || ''}
              onChange={handleChange}
              inputMode="numeric"
              maxLength={11}
              className={validationErrors.ContactNumber ? 'border-red-500' : ''}
            />
            {validationErrors.ContactNumber && (
              <p className="text-red-500 text-sm mt-1">{validationErrors.ContactNumber}</p>
            )}
          </div>

          <select name="Sex" value={form.Sex} onChange={handleChange} className="w-full border rounded px-3 py-2" required>
            <option value="">Select Sex</option>
            <option value="Male">Male</option>
            <option value="Female">Female</option>
          </select>

          {/* Status removed from Add Student modal; defaults to active */}

          <select name="IsPWD" value={form.IsPWD ? 'true' : 'false'} onChange={handleChange} className="w-full border rounded-lg px-3 py-2">
            <option value="false">Not PWD</option>
            <option value="true">PWD</option>
          </select>

          <div className="grid grid-cols-2 gap-4">
            <select
              name="Course"
              value={form.Course}
              onChange={handleChange}
              className="w-full border rounded px-3 py-2"
              required
              disabled={isLoadingCourses}
            >
              <option value="">
                {isLoadingCourses ? 'Loading courses...' : 'Select Course'}
              </option>
              {courses
                .filter(course => course.Status === 'active')
                .map((course) => (
                  <option key={course.CourseID} value={course.CourseCode}>
                    {course.CourseName}
                  </option>
                ))}
            </select>
            <Input
              name="YearLevel"
              placeholder="Year Level"
              type="number"
              min={1}
              max={4}
              value={form.YearLevel}
              onChange={handleChange}
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <Input name="Section" placeholder="Section" value={form.Section} onChange={handleChange} required />
            <Input
              name="DateOfEnrollment"
              type="date"
              value={form.DateOfEnrollment}
              onChange={handleChange}
              required
            />
          </div>

          <Input name="Address" placeholder="Address" value={form.Address || ''} onChange={handleChange} />
          <div className="grid grid-cols-2 gap-4">
            <Input name="GuardianName" placeholder="Guardian Name" value={form.GuardianName || ''} onChange={handleChange} />
            <div>
              <Input
                name="GuardianContact"
                placeholder="Guardian Contact"
                value={form.GuardianContact || ''}
                onChange={handleChange}
                className={validationErrors.GuardianContact ? 'border-red-500' : ''}
              />
              {validationErrors.GuardianContact && (
                <p className="text-red-500 text-sm mt-1">{validationErrors.GuardianContact}</p>
              )}
            </div>
          </div>
        </form>

        <DialogFooter className="mt-6 flex justify-end space-x-2">
          <DialogClose asChild>
            <Button variant="outline">Cancel</Button>
          </DialogClose>
          <Button
            type="submit"
            form="add-student-form"
            className="bg-green-900 text-white"
            disabled={isSubmitting || !isFormValid()}
            onClick={handleSubmit}
          >
            {isSubmitting ? 'Saving...' : 'Save'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
